import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul>
            <li>
              <Link href="/dynamic">/dynamic</Link>
            </li>
            <li>
              <Link href="/static">/static</Link>
            </li>
            <li>
              <Link href="/server-action">/server-action</Link>
            </li>
          </ul>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
